// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _05_Final_work;

#nullable disable

namespace _05_OlympicsDataAccess.Migrations
{
    [DbContext(typeof(OlympicsGamesDbContext))]
    [Migration("20250929043110_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MedalID")
                        .HasColumnType("int");

                    b.Property<int>("OlympicID")
                        .HasColumnType("int");

                    b.Property<int>("PlayerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedalID");

                    b.HasIndex("OlympicID");

                    b.HasIndex("PlayerID");

                    b.ToTable("Awards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MedalID = 1,
                            OlympicID = 1,
                            PlayerID = 1
                        },
                        new
                        {
                            Id = 2,
                            MedalID = 1,
                            OlympicID = 1,
                            PlayerID = 2
                        },
                        new
                        {
                            Id = 3,
                            MedalID = 3,
                            OlympicID = 1,
                            PlayerID = 3
                        },
                        new
                        {
                            Id = 4,
                            MedalID = 1,
                            OlympicID = 1,
                            PlayerID = 4
                        },
                        new
                        {
                            Id = 5,
                            MedalID = 2,
                            OlympicID = 1,
                            PlayerID = 5
                        },
                        new
                        {
                            Id = 6,
                            MedalID = 3,
                            OlympicID = 1,
                            PlayerID = 6
                        },
                        new
                        {
                            Id = 7,
                            MedalID = 2,
                            OlympicID = 1,
                            PlayerID = 7
                        },
                        new
                        {
                            Id = 8,
                            MedalID = 3,
                            OlympicID = 1,
                            PlayerID = 8
                        },
                        new
                        {
                            Id = 9,
                            MedalID = 2,
                            OlympicID = 1,
                            PlayerID = 9
                        },
                        new
                        {
                            Id = 10,
                            MedalID = 3,
                            OlympicID = 1,
                            PlayerID = 10
                        },
                        new
                        {
                            Id = 11,
                            MedalID = 2,
                            OlympicID = 1,
                            PlayerID = 11
                        },
                        new
                        {
                            Id = 12,
                            MedalID = 1,
                            OlympicID = 2,
                            PlayerID = 4
                        },
                        new
                        {
                            Id = 13,
                            MedalID = 3,
                            OlympicID = 2,
                            PlayerID = 5
                        },
                        new
                        {
                            Id = 14,
                            MedalID = 2,
                            OlympicID = 2,
                            PlayerID = 7
                        },
                        new
                        {
                            Id = 15,
                            MedalID = 3,
                            OlympicID = 2,
                            PlayerID = 8
                        },
                        new
                        {
                            Id = 16,
                            MedalID = 2,
                            OlympicID = 2,
                            PlayerID = 12
                        },
                        new
                        {
                            Id = 17,
                            MedalID = 1,
                            OlympicID = 2,
                            PlayerID = 13
                        },
                        new
                        {
                            Id = 18,
                            MedalID = 3,
                            OlympicID = 2,
                            PlayerID = 14
                        },
                        new
                        {
                            Id = 19,
                            MedalID = 1,
                            OlympicID = 2,
                            PlayerID = 15
                        },
                        new
                        {
                            Id = 20,
                            MedalID = 3,
                            OlympicID = 2,
                            PlayerID = 16
                        },
                        new
                        {
                            Id = 21,
                            MedalID = 1,
                            OlympicID = 2,
                            PlayerID = 17
                        },
                        new
                        {
                            Id = 22,
                            MedalID = 2,
                            OlympicID = 2,
                            PlayerID = 18
                        },
                        new
                        {
                            Id = 23,
                            MedalID = 1,
                            OlympicID = 3,
                            PlayerID = 19
                        },
                        new
                        {
                            Id = 24,
                            MedalID = 3,
                            OlympicID = 2,
                            PlayerID = 20
                        },
                        new
                        {
                            Id = 25,
                            MedalID = 3,
                            OlympicID = 3,
                            PlayerID = 21
                        },
                        new
                        {
                            Id = 26,
                            MedalID = 1,
                            OlympicID = 3,
                            PlayerID = 22
                        },
                        new
                        {
                            Id = 27,
                            MedalID = 3,
                            OlympicID = 3,
                            PlayerID = 23
                        },
                        new
                        {
                            Id = 28,
                            MedalID = 2,
                            OlympicID = 3,
                            PlayerID = 24
                        },
                        new
                        {
                            Id = 29,
                            MedalID = 3,
                            OlympicID = 3,
                            PlayerID = 25
                        },
                        new
                        {
                            Id = 30,
                            MedalID = 1,
                            OlympicID = 4,
                            PlayerID = 25
                        },
                        new
                        {
                            Id = 31,
                            MedalID = 1,
                            OlympicID = 4,
                            PlayerID = 26
                        },
                        new
                        {
                            Id = 32,
                            MedalID = 2,
                            OlympicID = 4,
                            PlayerID = 27
                        },
                        new
                        {
                            Id = 33,
                            MedalID = 3,
                            OlympicID = 4,
                            PlayerID = 28
                        },
                        new
                        {
                            Id = 34,
                            MedalID = 2,
                            OlympicID = 4,
                            PlayerID = 29
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.CountryHost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CountryHosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "France"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 4,
                            Name = "The USA"
                        },
                        new
                        {
                            Id = 5,
                            Name = "England"
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.CountryTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CountryTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "The USA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "France"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "England"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Canada"
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Medal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<string>("TypeOfMedal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Medals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Place = 0,
                            TypeOfMedal = "Gold"
                        },
                        new
                        {
                            Id = 2,
                            Place = 0,
                            TypeOfMedal = "Silver"
                        },
                        new
                        {
                            Id = 3,
                            Place = 0,
                            TypeOfMedal = "Bronze"
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.NameOfGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NameOfGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Surfing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Skateboarding"
                        },
                        new
                        {
                            Id = 3,
                            Name = "BMX Freestyle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Snowboarding"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Snowboarding Halfpipe"
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Olympic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountyHostID")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SeasonID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountyHostID");

                    b.HasIndex("SeasonID");

                    b.ToTable("Olympics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountyHostID = 1,
                            EndDate = new DateTime(2024, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonID = 1,
                            StartDate = new DateTime(2024, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CountyHostID = 2,
                            EndDate = new DateTime(2021, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonID = 1,
                            StartDate = new DateTime(2021, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CountyHostID = 3,
                            EndDate = new DateTime(2010, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonID = 2,
                            StartDate = new DateTime(2010, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CountyHostID = 4,
                            EndDate = new DateTime(2002, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonID = 2,
                            StartDate = new DateTime(2002, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CountyHostID = 5,
                            EndDate = new DateTime(2012, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonID = 2,
                            StartDate = new DateTime(2012, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountyTeamID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NameOfGameID")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountyTeamID");

                    b.HasIndex("NameOfGameID");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountyTeamID = 2,
                            Name = "Kauli",
                            NameOfGameID = 1,
                            Surname = "Vaast"
                        },
                        new
                        {
                            Id = 2,
                            CountyTeamID = 1,
                            Name = "Caroline",
                            NameOfGameID = 1,
                            Surname = "Marks"
                        },
                        new
                        {
                            Id = 3,
                            CountyTeamID = 2,
                            Name = "Johanne",
                            NameOfGameID = 1,
                            Surname = "Defay"
                        },
                        new
                        {
                            Id = 4,
                            CountyTeamID = 3,
                            Name = "Yuto",
                            NameOfGameID = 2,
                            Surname = "Horigome"
                        },
                        new
                        {
                            Id = 5,
                            CountyTeamID = 1,
                            Name = "Jagger",
                            NameOfGameID = 2,
                            Surname = "Eaton"
                        },
                        new
                        {
                            Id = 6,
                            CountyTeamID = 1,
                            Name = "Nyjah",
                            NameOfGameID = 2,
                            Surname = "Huston"
                        },
                        new
                        {
                            Id = 7,
                            CountyTeamID = 3,
                            Name = "Cocona",
                            NameOfGameID = 2,
                            Surname = "Hiraki"
                        },
                        new
                        {
                            Id = 8,
                            CountyTeamID = 4,
                            Name = "Sky",
                            NameOfGameID = 2,
                            Surname = "Brown"
                        },
                        new
                        {
                            Id = 9,
                            CountyTeamID = 4,
                            Name = "Kieran",
                            NameOfGameID = 3,
                            Surname = "Reilly"
                        },
                        new
                        {
                            Id = 10,
                            CountyTeamID = 2,
                            Name = "Anthony",
                            NameOfGameID = 3,
                            Surname = "Jeanjean"
                        },
                        new
                        {
                            Id = 11,
                            CountyTeamID = 1,
                            Name = "Perris",
                            NameOfGameID = 3,
                            Surname = "Benegas"
                        },
                        new
                        {
                            Id = 12,
                            CountyTeamID = 3,
                            Name = "Kanoa",
                            NameOfGameID = 1,
                            Surname = "Igarashi"
                        },
                        new
                        {
                            Id = 13,
                            CountyTeamID = 1,
                            Name = "Carissa",
                            NameOfGameID = 1,
                            Surname = "Moore"
                        },
                        new
                        {
                            Id = 14,
                            CountyTeamID = 3,
                            Name = "Amuro",
                            NameOfGameID = 1,
                            Surname = "Tsuzuki"
                        },
                        new
                        {
                            Id = 15,
                            CountyTeamID = 3,
                            Name = "Sakura",
                            NameOfGameID = 2,
                            Surname = "Yosozumi"
                        },
                        new
                        {
                            Id = 16,
                            CountyTeamID = 4,
                            Name = "Declan",
                            NameOfGameID = 3,
                            Surname = "Brooks"
                        },
                        new
                        {
                            Id = 17,
                            CountyTeamID = 4,
                            Name = "Charlotte",
                            NameOfGameID = 3,
                            Surname = "Worthington"
                        },
                        new
                        {
                            Id = 18,
                            CountyTeamID = 1,
                            Name = "Hannah",
                            NameOfGameID = 3,
                            Surname = "Roberts"
                        },
                        new
                        {
                            Id = 19,
                            CountyTeamID = 1,
                            Name = "Seth",
                            NameOfGameID = 4,
                            Surname = "Wescott"
                        },
                        new
                        {
                            Id = 20,
                            CountyTeamID = 5,
                            Name = "Mike",
                            NameOfGameID = 4,
                            Surname = "Robertson"
                        },
                        new
                        {
                            Id = 21,
                            CountyTeamID = 2,
                            Name = "Tony",
                            NameOfGameID = 4,
                            Surname = "Ramoin"
                        },
                        new
                        {
                            Id = 22,
                            CountyTeamID = 1,
                            Name = "Shaun",
                            NameOfGameID = 5,
                            Surname = "White"
                        },
                        new
                        {
                            Id = 23,
                            CountyTeamID = 1,
                            Name = "Scott",
                            NameOfGameID = 5,
                            Surname = "Lago"
                        },
                        new
                        {
                            Id = 24,
                            CountyTeamID = 1,
                            Name = "Hannah",
                            NameOfGameID = 5,
                            Surname = "Teter"
                        },
                        new
                        {
                            Id = 25,
                            CountyTeamID = 1,
                            Name = "Kelly",
                            NameOfGameID = 5,
                            Surname = "Clark"
                        },
                        new
                        {
                            Id = 26,
                            CountyTeamID = 1,
                            Name = "Ross",
                            NameOfGameID = 5,
                            Surname = "Powers"
                        },
                        new
                        {
                            Id = 27,
                            CountyTeamID = 1,
                            Name = "Danny",
                            NameOfGameID = 5,
                            Surname = "Kass"
                        },
                        new
                        {
                            Id = 28,
                            CountyTeamID = 1,
                            Name = "Jarret (J.J.)",
                            NameOfGameID = 5,
                            Surname = "Thomas"
                        },
                        new
                        {
                            Id = 29,
                            CountyTeamID = 2,
                            Name = "Doriane",
                            NameOfGameID = 5,
                            Surname = "Vidal"
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Seasons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Summer"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Winter"
                        });
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Award", b =>
                {
                    b.HasOne("_05_OlympicsDataAccess.Entities.Medal", "Medal")
                        .WithMany("Awards")
                        .HasForeignKey("MedalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05_OlympicsDataAccess.Entities.Olympic", "Olympic")
                        .WithMany("Awards")
                        .HasForeignKey("OlympicID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05_OlympicsDataAccess.Entities.Player", "Player")
                        .WithMany("Awards")
                        .HasForeignKey("PlayerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medal");

                    b.Navigation("Olympic");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Olympic", b =>
                {
                    b.HasOne("_05_OlympicsDataAccess.Entities.CountryHost", "CountryHost")
                        .WithMany("Olympics")
                        .HasForeignKey("CountyHostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05_OlympicsDataAccess.Entities.Season", "Season")
                        .WithMany("Olympics")
                        .HasForeignKey("SeasonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryHost");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Player", b =>
                {
                    b.HasOne("_05_OlympicsDataAccess.Entities.CountryTeam", "CountryTeam")
                        .WithMany("Players")
                        .HasForeignKey("CountyTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_05_OlympicsDataAccess.Entities.NameOfGame", "NameOfGame")
                        .WithMany("Players")
                        .HasForeignKey("NameOfGameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CountryTeam");

                    b.Navigation("NameOfGame");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.CountryHost", b =>
                {
                    b.Navigation("Olympics");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.CountryTeam", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Medal", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.NameOfGame", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Olympic", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Player", b =>
                {
                    b.Navigation("Awards");
                });

            modelBuilder.Entity("_05_OlympicsDataAccess.Entities.Season", b =>
                {
                    b.Navigation("Olympics");
                });
#pragma warning restore 612, 618
        }
    }
}
